spring:
  task:
    scheduling:
      pool:
        size: 5
openai:
  model: ${OPENAI_MODEL:text-davinci-003}
  apiKey: ${OPENAI_API_KEY:你的apiKey}
zsxq:
  cookie: ${ZSXQ_COOKIE:你的星球cookie}
  groupId: ${ZSXQ_GROUP_ID:你的星球id}
  silenced: ${ZSXQ_SILENCED:true}
scheduler:
  list:
    - name: chatbot1
      monitor: zsxq
      answerer: openai
      cron: '0/30 * * * * ?'